services:
  mongo:
    image: mongo:7.0.5
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_DB_ROOT_USERNAME: root
      MONGO_DB_ROOT_PASSWORD: password
      MONGO_DB_DATABASE: product-service
    volumes:
      - ./docker/mongodb/data:/data/db
